# Generated by Django 3.0.7 on 2020-07-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=250)),
                ('P_price', models.IntegerField()),
                ('P_gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('P_category', models.CharField(choices=[('C', 'Clothing'), ('E', 'Electronics'), ('S', 'Sports'), ('Ed', 'Education')], max_length=20)),
                ('P_sizes', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('P_desc', models.TextField()),
                ('P_image', models.ImageField(blank=True, upload_to='product_images/')),
                ('disc_price', models.IntegerField(blank=True, null=True)),
                ('P_disc', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
