# Generated by Django 3.0.1 on 2020-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=100)),
                ('P_price', models.IntegerField()),
                ('P_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('P_sizes', models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10)),
                ('P_desc', models.TextField()),
                ('P_image', models.ImageField(blank=True, upload_to='product_images/')),
            ],
        ),
    ]
