# Generated by Django 3.0.1 on 2020-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.CharField(choices=[('C', 'Clothing'), ('E', 'Electronics'), ('S', 'Sports'), ('Ed', 'Education')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
