# Generated by Django 3.0.1 on 2020-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_p_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=5),
        ),
    ]
