# Generated by Django 3.0.1 on 2020-02-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200204_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_category',
            new_name='P_category',
        ),
    ]
