# Generated by Django 3.0.5 on 2020-06-13 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='product',
            name='P_offer',
            field=models.CharField(choices=[('N', 'New'), ('M', 'Medium'), ('O', 'Old')], default='New', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='disc_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
