# Generated by Django 3.0.7 on 2020-07-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200613_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_offer',
            field=models.BooleanField(default=False),
        ),
    ]
