# Generated by Django 3.0.7 on 2020-07-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200705_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='P_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='P_disc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
