# Generated by Django 3.0.7 on 2020-07-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200705_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_name',
            field=models.CharField(max_length=250),
        ),
    ]
