# Generated by Django 3.0.1 on 2019-12-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_desc', models.TextField()),
                ('product_date', models.DateField(auto_now_add=True)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
