# Generated by Django 3.0.7 on 2020-07-01 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200614_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
